[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NETLIFY_USE_YARN = "true"
  NODE_VERSION = "20"
  NODE_OPTIONS = "--no-optional"
  VITE_FIREBASE_API_KEY = "AIzaSyC9DdJWQavE5mqlJyRAonBEmEiaEqU6SQE"
  VITE_FIREBASE_AUTH_DOMAIN = "project-eva-7b42d.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "project-eva-7b42d"
  VITE_FIREBASE_STORAGE_BUCKET = "project-eva-7b42d.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "280210511185"
  VITE_FIREBASE_APP_ID = "1:280210511185:web:8da047c6931b71610c6f70"
  VITE_FIREBASE_MEASUREMENT_ID = "G-RWZ1T5L346"
  VITE_TELEGRAM_BOT_TOKEN = "7811936235:AAHvcYPIFE7K_V6y6aQ-AcTsNlmrXbZMc_0"
  VITE_TELEGRAM_CHAT_ID = "772557039"
